### ISSUE TITLE
C++ version

### ISSUE THREAD

**Issue by shrutisharmavsco** [shehzan10/glContext#1]
Do you happen to have a C++ version of glContext.hpp which does not use C strings and printf's, etc. 

Also, is there is a reason for you to name your file .hpp if the code is basically all C?

Thanks.

**Comment by shehzan10** [comment]
This was actually taken from a project I was working on and decided to make it standalone. Hence the C-style and the hpp header. You can change it to a .h file if you wish and it wont make any difference.

**Comment by shrutisharmavsco** [comment]
Thanks. I am hoping to convert it to C++ and use it though.
